I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    r "Главный герой Костя видит сон, где еле различимая фигура со светом говорит непонятные вещи, где он разбирает только фразу «Ты должен написать код»."
Exception: Sayer 'r' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script
    r "Главный герой Костя видит сон, где еле различимая фигура со светом говорит непонятные вещи, где он разбирает только фразу «Ты должен написать код»."
  File "D:\Projects\OPD_game\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "D:\Projects\OPD_game\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Projects\OPD_game\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'r' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
ABSOLUTION 1.0
Mon Nov 18 12:48:05 2024
